
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Inc/rcc.h"
#include "../Inc/gpio.h"

int main(void)
{
    mcu_clk_init();
    peripheral_clk_init();
    gpio_init();
    /* Loop forever */
	for(;;){
        LED_pin_low();
        for(uint32_t i = 0; i < 500000; i++){

        };
        LED_pin_high();
        for(uint32_t i = 0; i < 500000; i++){

        };
    };
}
